database:
  url: "sqlite:///../results/app.db"

security:
  jwt_secret: "CHANGE_ME_SECRET_KEY"

rag:
  embedding_model_path: "../models/multilingual_e5_large"
  llm_model_path: "../models/vinallama-2.7b-chat"
  faiss_index_path: "../results/all_faiss.index"
  embeddings_pkl_path: "../results/all_embeddings.pkl"
